PLAYER_COLUMNS = [
    "gsis_id",
    "display_name",
    "common_first_name",
    "first_name",
    "last_name",
    "football_name",
    "suffix",
    "birth_date",
    "position_group",
    "position",
    "height",
    "weight",
    "headshot",
    "college_name",
    "college_conference",
    "rookie_season",
    "last_season",
    "draft_year",
    "draft_round",
    "draft_pick",
    "draft_team",
]

EXTERNAL_ID_COLUMNS = [
    "gsis_id",
    "esb_id",
    "nfl_id",
    "pfr_id",
    "pff_id",
    "otc_id",
    "espn_id",
    "smart_id",
]

PLAYER_STATUS_COLUMNS = [
    "gsis_id",
    "latest_team",
    "jersey_number",
    "position",
    "status",
    "ngs_status",
    "ngs_status_short_description",
    "years_of_experience",
    "last_season",
]

TEAM_COLUMNS = [
    "team_abbr",
    "team_id",
    "team_name",
    "team_nick",
    "team_conf",
    "team_division",
    "team_color",
    "team_color2",
    "team_logo_espn",
    "team_wordmark",
    "team_logo_squared",
]

WEEKLY_STAT_COLUMNS = [
    "player_id",
    "season",
    "week",
    "season_type",
    "game_id",
    "team",
    "opponent_team",
    "position",
    "position_group",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "passing_2pt_conversions",
    "pacr",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "rushing_2pt_conversions",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "receiving_2pt_conversions",
    "racr",
    "target_share",
    "air_yards_share",
    "wopr",
    "fantasy_points",
    "fantasy_points_ppr",
]

WEEKLY_ROSTER_COLUMNS = [
    "gsis_id",
    "season",
    "week",
    "game_type",
    "team",
    "position",
    "depth_chart_position",
    "jersey_number",
    "status",
    "status_description_abbr",
    "years_exp",
]

GAME_COLUMNS = [
    "game_id",
    "season",
    "game_type",
    "week",
    "gameday",
    "weekday",
    "gametime",
    "away_team",
    "away_score",
    "home_team",
    "home_score",
    "location",
    "overtime",
    "away_rest",
    "home_rest",
    "spread_line",
    "total_line",
    "div_game",
    "roof",
    "surface",
    "temp",
    "wind",
    "away_qb_id",
    "home_qb_id",
    "away_qb_name",
    "home_qb_name",
    "away_coach",
    "home_coach",
    "stadium_id",
    "stadium",
]

SNAP_COUNT_COLUMNS = [
    "game_id",
    "season",
    "game_type",
    "week",
    "pfr_player_id",
    "position",
    "team",
    "opponent",
    "offense_snaps",
    "offense_pct",
    "defense_snaps",
    "defense_pct",
    "st_snaps",
    "st_pct",
]

TEAM_WEEKLY_STAT_COLUMNS = [
    "season",
    "week",
    "season_type",
    "game_id",
    "team",
    "opponent_team",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "passing_2pt_conversions",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "rushing_2pt_conversions",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "receiving_2pt_conversions",
]

# Numeric outputs produced by player_season_stats.py. Keeping these beside the
# processed schemas lets ingestion, processing, and model-facing tools share one
# field contract.
PLAYER_SEASON_ADDITIVE_COLUMNS = [
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_2pt_conversions",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_2pt_conversions",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_2pt_conversions",
    "fantasy_points",
    "fantasy_points_ppr",
]

PLAYER_SEASON_DERIVED_COLUMNS = [
    "passing_epa",
    "rushing_epa",
    "receiving_epa",
    "completion_percentage",
    "passing_yards_per_attempt",
    "passing_epa_per_attempt",
    "passing_cpoe",
    "pacr",
    "rushing_yards_per_carry",
    "rushing_epa_per_carry",
    "catch_percentage",
    "receiving_yards_per_reception",
    "receiving_yards_per_target",
    "receiving_epa_per_target",
    "racr",
    "fantasy_points_per_game",
    "fantasy_points_ppr_per_game",
]

# Raw nflverse depth-chart schema used through the 2024 season.
LEGACY_DEPTH_CHART_COLUMNS = [
    "season",
    "club_code",
    "week",
    "game_type",
    "depth_team",
    "football_name",
    "formation",
    "gsis_id",
    "jersey_number",
    "position",
    "depth_position",
    "full_name",
]

# Raw nflverse timestamped depth-chart schema used from the 2025 season onward.
TIMESTAMPED_DEPTH_CHART_COLUMNS = [
    "dt",
    "team",
    "player_name",
    "espn_id",
    "gsis_id",
    "pos_grp_id",
    "pos_grp",
    "pos_id",
    "pos_name",
    "pos_abb",
    "pos_slot",
    "pos_rank",
]

# Source-independent schema written to processed depth-chart tables.
NORMALIZED_DEPTH_CHART_COLUMNS = [
    "season",
    "week",
    "season_type",
    "snapshot_at",
    "team",
    "player_name",
    "gsis_id",
    "espn_id",
    "formation",
    "position_group",
    "position_name",
    "position",
    "position_slot",
    "depth_rank",
    "jersey_number",
]
