-- Structured NFL data generated by backend/processing/workflows/.
-- Keep column names aligned with the processed Parquet files so ingestion can
-- upsert rows without a translation layer.

create table public.players (
    player_id uuid primary key,
    gsis_id text not null unique,
    display_name text not null,
    common_first_name text not null,
    first_name text not null,
    last_name text not null,
    football_name text,
    suffix text,
    birth_date date,
    position_group text not null,
    position text not null,
    height integer,
    weight integer,
    headshot text,
    college_name text not null,
    college_conference text,
    rookie_season integer not null,
    last_season integer not null,
    draft_year integer,
    draft_round integer,
    draft_pick integer,
    draft_team text
);

create table public.player_status (
    player_id uuid primary key references public.players(player_id) on delete cascade,
    gsis_id text not null unique references public.players(gsis_id) on delete cascade,
    latest_team text not null,
    jersey_number text,
    position text not null,
    status text not null,
    ngs_status text,
    ngs_status_short_description text,
    years_of_experience integer not null,
    last_season integer not null
);

create table public.games (
    game_id text primary key,
    season integer not null,
    game_type text not null,
    week integer not null,
    gameday date not null,
    weekday text not null,
    gametime text not null,
    away_team text not null,
    away_score integer not null,
    home_team text not null,
    home_score integer not null,
    location text not null,
    overtime integer not null,
    away_rest integer not null,
    home_rest integer not null,
    spread_line double precision not null,
    total_line double precision not null,
    div_game integer not null,
    roof text not null,
    surface text not null,
    temp integer,
    wind integer,
    away_qb_id text not null,
    home_qb_id text not null,
    away_qb_name text not null,
    home_qb_name text not null,
    away_coach text not null,
    home_coach text not null,
    stadium_id text not null,
    stadium text not null
);

create table public.player_weekly_stats (
    player_id uuid not null references public.players(player_id) on delete cascade,
    gsis_id text not null,
    season integer not null,
    week integer not null,
    season_type text not null,
    game_id text not null references public.games(game_id) on delete cascade,
    team text not null,
    opponent_team text not null,
    position text not null,
    position_group text not null,
    completions integer not null,
    attempts integer not null,
    passing_yards integer not null,
    passing_tds integer not null,
    passing_interceptions integer not null,
    sacks_suffered integer not null,
    sack_yards_lost integer not null,
    passing_air_yards integer not null,
    passing_yards_after_catch integer not null,
    passing_first_downs integer not null,
    passing_epa double precision,
    passing_cpoe double precision,
    passing_2pt_conversions integer not null,
    pacr double precision,
    carries integer not null,
    rushing_yards integer not null,
    rushing_tds integer not null,
    rushing_fumbles integer not null,
    rushing_fumbles_lost integer not null,
    rushing_first_downs integer not null,
    rushing_epa double precision,
    rushing_2pt_conversions integer not null,
    receptions integer not null,
    targets integer not null,
    receiving_yards integer not null,
    receiving_tds integer not null,
    receiving_fumbles integer not null,
    receiving_fumbles_lost integer not null,
    receiving_air_yards integer not null,
    receiving_yards_after_catch integer not null,
    receiving_first_downs integer not null,
    receiving_epa double precision,
    receiving_2pt_conversions integer not null,
    racr double precision,
    target_share double precision not null,
    air_yards_share double precision not null,
    wopr double precision not null,
    fantasy_points double precision not null,
    fantasy_points_ppr double precision not null,

    primary key (player_id, game_id)
);

-- Common model-tool query paths.
create index players_display_name_idx on public.players (lower(display_name));
create index games_season_week_idx on public.games (season, week);
create index games_away_team_season_idx on public.games (away_team, season, week);
create index games_home_team_season_idx on public.games (home_team, season, week);
create index player_weekly_stats_player_season_idx
    on public.player_weekly_stats (player_id, season, week);
create index player_weekly_stats_season_week_idx
    on public.player_weekly_stats (season, week);
create index player_weekly_stats_team_season_idx
    on public.player_weekly_stats (team, season, week);

-- No public policies yet. Backend secret-key clients bypass RLS, while
-- publishable/anonymous clients cannot read these tables.
alter table public.players enable row level security;
alter table public.player_status enable row level security;
alter table public.games enable row level security;
alter table public.player_weekly_stats enable row level security;
